[package]
name = "kiln"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
anyrender = "0.11"
anyrender_vello = "0.12"
atomic_refcell = "0.1.14"
blitz-dom = "0.3.0-beta.1"
blitz-html = "0.3.0-beta.1"
blitz-paint = "0.3.0-beta.1"
blitz-traits = "0.3.0-beta.1"
keyboard-types = "0.7"
parley = { version = "0.10", features = ["complex-scripts"] }
png = "0.18.1"
rquickjs = { version = "0.12.2", features = ["macro", "futures"] }
winit = "0.30.13"
